sudo: false
language: php


php:
  - 5.6

directories:
  - $HOME/.composer/cache

install:
  - composer install -n

before_script:
  - nohup app/console server:run --router=../app/router_test.php --docroot=web/ &

script:
  - phpunit -c app
  - bin/phpspec run
  - bin/behat
