language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install --prefer-source -n
  - nohup app/console server:run --router=../app/router_test.php --docroot=web/ &

script:
  - phpunit -c app
  - bin/phpspec run
  - bin/behat
